# Generated by Django 4.1.7 on 2023-03-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("idConta", models.AutoField(primary_key=True, serialize=False)),
                ("idPessoa", models.IntegerField()),
                ("saldo", models.IntegerField(blank=True, default=0)),
                ("limiteSaqueDiario", models.IntegerField(blank=True, null=True)),
                ("flagAtivo", models.BooleanField(default=True)),
                ("tipoConta", models.IntegerField(default=0)),
                ("dataCriacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
