# Generated by Django 4.1.7 on 2023-03-11 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="idPessoa",
        ),
    ]
