# Generated by Django 4.1.7 on 2023-03-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("idTransacao", models.AutoField(primary_key=True, serialize=False)),
                ("valor", models.IntegerField()),
                ("dataTransacao", models.DateTimeField(auto_now_add=True)),
                (
                    "idConta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
