# Generated by Django 4.1.7 on 2023-03-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("idPessoa", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=32)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("dataNascimento", models.CharField(max_length=10)),
            ],
        ),
    ]
